location_dict = {
	# Continent to planet
	'asia' : 'earth',
	'africa' : 'earth',
	'europe' : 'earth',
	'south america' : 'earth',
	'north america' : 'earth',
	'diacria' : 'mars',
	'tharsis' : 'mars',

	# Countries to continent
	'china' : 'asia',
	'united states' : 'north america',
	'pakistan' : 'asia',
	'india' : 'asia',
	'nigeria' : 'africa',
	'japan' : 'asia',
	'turkey' : 'europe',
	'russia' : 'asia',
	'brazil' : 'south america',
	'indonesia' : 'asia',
	'egypt' : 'africa',
	'mexico' : 'north america',

	# Cities to country
	'shanghai' : 'china',
	'beijing' : 'china',
	'tianjin' : 'china',
	'guangzhou' : 'china',
	'karachi' : 'pakistan',
	'delhi' : 'india',
	'mumbai' : 'india',
	'lagos' : 'nigeria',
	'instanbul' : 'turkey',
	'tokyo' : 'japan',
	'moscow' : 'russia',
	'sao paulo' : 'brazil',
	'jakarta' : 'indonesia',
	'cairo' : 'egypt',
	'mexico city' : 'mexico',

	# State to country
	'illinois' : 'united states',
	'texas' : 'united states',
	'new york' : 'united states',
	'california' : 'united states',
	'pennsylvania' : 'united states',
	'arizona' : 'united states',
	'ohio' : 'united states',
	'florida' : 'united states',
	'north carolina' : 'united states',
	'michigan' : 'united states',

	# Cities to state
	'chicago' : 'illinois',
	'new york city' : 'new york',
	'los angeles' : 'california',
	'houston' : 'texas',
	'philadelphia' : 'pennsylvania', 
	'phoenix' : 'arizona',
	'san antonio' : 'texas',
	'san diego' : 'california',
	'san jose' : 'california',
	'dallas' : 'texas',
	'columbus' : 'ohio',
	'jacksonville' : 'florida',
	'austin' : 'texas',
	'charlotte' : 'north carolina',
	'detroit' : 'michigan'
}
